package soundsynthesizer.synthesis;

import java.util.concurrent.CopyOnWriteArrayList;

/**
 * This class is responsible for running and managing the whole process of synthesis:
 * creating voices, mixing them, applying effects and sending to output.
 *
 * @author Marek Bobrowski
 */
public class Synthesizer implements Runnable {
    /**
     * A list of voices that are currently being generated.
     */
    private final CopyOnWriteArrayList <Voice> voices = new CopyOnWriteArrayList<>();

    /**
     * A list of voices that are going to be removed after the current buffer.
     */
    private final CopyOnWriteArrayList <Voice> voicesToBeRemoved = new CopyOnWriteArrayList<>();

    /**
     * A list of voices that are going to be generated within the next buffer.
     */
    private final CopyOnWriteArrayList <Voice> voicesToBeAdded = new CopyOnWriteArrayList<>();

    /**
     * The delay effect used to process the sound of this synthesizer.
     */
    private final Delay delay = new Delay();

    /**
     * The reverberation effect used to process the sound of this synthesizer.
     */
    private final Reverb reverb = new Reverb();

    /**
     * The converter that is going to stream the signal from this synthesizer to a sound card.
     */
    private final Converter converter = new Converter();

    /**
     * The envelope settings of the voices generated by this synthesizer.
     */
    private final EnvelopeSettings envelopeSettings = new EnvelopeSettings();

    /**
     * The settings of the oscillators that generate sound for this synthesizer.
     */
    private final OscillatorSettings oscillatorSettings = new OscillatorSettings();

    /**
     * The output loudness of this synthesizer.
     */
    private final Volume volume = new Volume();

    /**
     * Tells if this synthesizer should keep buffering new sound.
     */
    private boolean keepBuffering = false;

    /**
     * Empty constructor.
     */
    public Synthesizer() {
    }

    /**
     * Add the voice to the "waiting room" - 'voicesToBeAdded' list.
     * @param newVoice The voice to be created.
     */
    public void createNewVoice(Voice newVoice) {
        voicesToBeAdded.add(newVoice);
    }

    /**
     * Add the voice to the 'voicesToBeRemoved' list.
     * @param voice The voice to be removed.
     */
    public void endVoice(Voice voice) {
        voicesToBeRemoved.add(voice);
    }

    /**
     * Remove the 'voicesToBeRemoved' list from the 'voices' list.
     */
    private void endFinishedVoices() {
        for(Voice n: voicesToBeRemoved) {
            voices.remove(n);
        }
        voicesToBeRemoved.clear();
    }

    /**
     * Add all voices from the 'voicesToBeAdded' list to the 'voices' list.
     */
    private void acceptNewVoices() {
        voices.addAll(voicesToBeAdded);
        voicesToBeAdded.clear();
    }

    /**
     * Gathers buffers from all the voices.
     * @param bufferSize The number of frames of a sound buffer.
     * @return The array of sound buffers created by all the voices.
     */
    private double[][][] gatherBuffersFromAllVoices(int bufferSize) {
        double[][][] allVoiceBuffers = new double[voices.size()][2][bufferSize];
        int index = 0;
        for(Voice n : voices) {
            if (index >= allVoiceBuffers.length) {
                break;
            }
            allVoiceBuffers[index] = n.prepareBuffer(bufferSize);
            index++;
        }
        return allVoiceBuffers;
    }

    /**
     * Returns mixed and processed sound of all buffers.
     * @param allVoiceBuffers The buffers to be mixed and processed.
     * @param bufferSize The number of frames of a sound buffer.
     */
    private double[][] returnProcessedVoices(double[][][] allVoiceBuffers, int bufferSize) {
        double[][] mixedVoices = Voice.mixAndNormalizeVoices(allVoiceBuffers, bufferSize);
        delay.processBuffer(mixedVoices);
        mixedVoices = reverb.createProcessedBuffer(mixedVoices);
        volume.processBuffer(mixedVoices);
        return mixedVoices;
    }

    /**
     * Stops streaming the sound to the sound card.
     */
    public void finishWork() {
        keepBuffering = false;
        converter.stopStreaming();
    }

    /**
     * Continuous process of buffering the sound:
     * 1. Add voices that have been recently triggered.
     * 2. Remove the voices that ended.
     * 3. Gather the buffers from all the existing voices.
     * 4. Mix and process the gathered buffers.
     * 5. Send the processed sound to the output.
     */
    @Override
    public void run() {
        double[][][] allVoiceBuffers;
        this.keepBuffering = true;
        while (keepBuffering) {
            int bufferSize = converter.getBufferSize();
            acceptNewVoices();
            endFinishedVoices();
            allVoiceBuffers = gatherBuffersFromAllVoices(bufferSize);
            double[][] processedVoices = returnProcessedVoices(allVoiceBuffers, bufferSize);
            converter.streamBuffer(processedVoices);
        }
    }

    /**
     * Get the delay effect used to process the sound of this synthesizer.
     * @return The delay effect used to process the sound of this synthesizer.
     */
    public Delay getDelay() {
        return delay;
    }

    /**
     * Get reverberation effect used to process the sound of this synthesizer.
     * @return The reverberation effect used to process the sound of this synthesizer.
     */
    public Reverb getReverb() {
        return reverb;
    }

    /**
     * Get the envelope settings of the voices generated by this synthesizer.
     * @return The envelope settings of the voices played by this synthesizer.
     */
    public EnvelopeSettings getEnvelopeSettings() {
        return envelopeSettings;
    }

    /**
     * Get the settings of the oscillators that generate sound for this synthesizer.
     * @return The settings of the oscillators that generate sound for this synthesizer.
     */
    public OscillatorSettings getOscillatorSettings() {
        return oscillatorSettings;
    }

    /**
     * Get the converter that is going to stream the signal from this synthesizer to a sound card.
     * @return The converter that is going to stream the signal from this synthesizer to a sound card.
     */
    public Converter getConverter() {
        return converter;
    }

    /**
     * Returns the object responsible for controlling the volume of this synthesizer.
     * @return The object responsible for controlling the volume of this synthesizer.
     */
    public Volume getVolume() {
        return volume;
    }
}
